version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb

  nginx:
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.frontend.rule=Host:server.localhost

  db:
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
